#ifndef FXP_OPERATORS_H
#define FXP_OPERATORS_H

#include "fxp_types.h"

fxp16_t fxp_add(fxp16_t lhs, fxp16_t rhs);

fxp16_t fxp_sub(fxp16_t lhs, fxp16_t rhs);

fxp16_t fxp_mul(fxp16_t lhs, fxp16_t rhs);

/**
* @note  INT 0 is generated by IDIV or DIV when the result won't fit into the
* destination, or the divisor is 0.
* The 8088, 8086, V20, and V30 push the CS:IP of the instruction *FOLLOWING* the DIV
* or IDIV instruction that generated the division-by-zero error condition.
* Thus, execution will continue.
* The 80286 and 80386, however, push the CS:IP of the *SAME* DIV or IDIV instruction and get
* stuck in an infinite loop!
*/
fxp16_t fxp_div(fxp16_t lhs, fxp16_t rhs);

inline fxp16_t fxp_pow2(fxp16_t x) {
	return fxp_mul(x, x);
}

fxp16_t fxp_sqrt(fxp16_t x);

#endif
